webserver/badge_project/badge_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from tastypie.api import Api

from api.resources import JoinedEventActivityResource, EarnedBadgeActivityResource, UserResource, BadgeResource, EventResource, ImageResource, AttendeesResource

api_resources = Api(api_name='resources')
api_resources.register(UserResource())
api_resources.register(BadgeResource())
api_resources.register(EventResource())
api_resources.register(ImageResource())
api_resources.register(JoinedEventActivityResource())
api_resources.register(EarnedBadgeActivityResource())
api_resources.register(AttendeesResource())


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('badges/', include('badges.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('events/', include('events.urls')),
    path('api/', include(api_resources.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/badge_project/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventView.as_view(), name='events'),
    path('event_pin/', views.EventPin.as_view(), name='event_pin'),
    path('<int:pk>/event_profile/', views.EventProfile.as_view(), name='event_profile'),
    path('create_event/', views.CreateEvent.as_view(), name='create_event'),
]

webserver/badge_project/users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from .views import LoginView

current_app = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('<username>/profile_page/', views.ProfilePage.as_view(), name='profile_page'),
    path('<username>/profile_page/edit', views.ProfileUpdate.as_view(), name='edit_profile'),
    path('<int:pk>/profile_page/delete/', views.DeleteUser.as_view(), name='delete_profile'),
    url(r'^login/$', LoginView.as_view(), name='login'),
]

webserver/badge_project/templates/home.html
{% extends 'nav/nav.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="container-fluid fill bg-warning text-dark verticalCentered">
            <div class="row m-0 h-100">
                <div class="col-md-6 m-4 mx-auto my-auto">
                    <div class="row mt-4 mb-2 justify-content-center">
                        <h1 class="text-light font-italic">Welcome to the site {{ user.username|capfirst }}</h1>
                    </div>
                    <div class="row mt-4 mb-2 justify-content-center">
                        <button class="btn btn-outline-light my-2 btn-lg font-weight-bold"
                                onclick="location.href='{% url 'events:event_pin' %}'">Enter a new event
                        </button>
                    </div>
                </div>
            </div>
        </div>

    {% else %}

        <div class="container-fluid bg-info" style="height: 100%;">
            <div class="row h-100">
                <div class="col-md-4 mx-auto my-auto">
                    <div class="row mb-2 justify-content-center">
                        <h1 class="text-light">You are not logged in</h1>
                    </div>
                    <div class="row mt-4 mb-2 justify-content-center">
                        <div class="col-lg-9">
                            <button class="btn btn-lg btn-light btn-block" onclick="location.href='{% url 'login' %}'">
                                Go to login
                                page
                            </button>
                        </div>
                    </div>

                    <div class="row mt-2 mb-2 justify-content-center">
                        <div class="col-lg-9">
                            <button class="btn btn-lg btn-outline-light btn-block"
                                    onclick="location.href='{% url 'signup' %}'">Create new
                                account
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

webserver/badge_project/templates/signup.html
{% extends 'nav/nav.html' %}

{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock %}

{% block content %}

    {% load static %}

    {% crispy form %}

{% endblock %}