webserver/badge_project/badge_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from tastypie.api import Api

from api.resources import JoinedEventActivityResource, EarnedBadgeActivityResource, UserResource, BadgeResource, EventResource, ImageResource, AttendeesResource

api_resources = Api(api_name='resources')
api_resources.register(UserResource())
api_resources.register(BadgeResource())
api_resources.register(EventResource())
api_resources.register(ImageResource())
api_resources.register(JoinedEventActivityResource())
api_resources.register(EarnedBadgeActivityResource())
api_resources.register(AttendeesResource())


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('badges/', include('badges.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('events/', include('events.urls')),
    path('api/', include(api_resources.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/badge_project/badges/urls.py
from django.urls import path

from . import views

app_name = 'badges'
urlpatterns = [
    path('create_new_badge/', views.BadgeCreate.as_view(), name='create_new_badge'),
]

webserver/badge_project/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventView.as_view(), name='events'),
    path('event_pin/', views.EventPin.as_view(), name='event_pin'),
    path('<int:pk>/event_profile/', views.EventProfile.as_view(), name='event_profile'),
    path('create_event/', views.CreateEvent.as_view(), name='create_event'),
]

webserver/badge_project/users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from .views import LoginView

current_app = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('<username>/profile_page/', views.ProfilePage.as_view(), name='profile_page'),
    path('<username>/profile_page/edit', views.ProfileUpdate.as_view(), name='edit_profile'),
    path('<int:pk>/profile_page/delete/', views.DeleteUser.as_view(), name='delete_profile'),
    url(r'^login/$', LoginView.as_view(), name='login'),
]

webserver/badge_project/templates/nav/nav.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'badges/style.css' %}">
<div id="fb-root"></div>
<script async defer crossorigin="anonymous"
        src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2"></script>
<script type="text/javascript" src="{% static 'badges/switchEventProfileContent.js' %}"></script>


<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="">
    <title>The Honey Badgers</title>
    <meta property="og:url" content="http://192.168.50.50:8080/"/>
    <meta property="og:title" content="The Honey Badgers"/>
    <meta property="og:type" content="Website"/>
    <meta property="og:description" content="description" content="School Project for class ID202712 NTNU Aalesund Bachelor of Computer Engineering.
                Badge collection similar to achievements in games."/>
    <meta property="og:authors" content="Espen Vad, Pernille Skytterholm, Jahn-Willy Nøstdahl and Markus Randa.">
    <meta property="og:image" content="https://i.imgur.com/Jn9nD1U.jpg"/>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <title>Badges</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top m-0 navStyling"
     style="box-shadow: 0 5px 10px -5px rgba(50, 50, 50, 0.5);">
    <a class="navbar-brand" href="/">The HoneyBadgers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'events:events' %}">Events <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'badges:create_new_badge' %}">Create New Badge</a>
                </li>
            </ul>

            <ul class="navbar-nav my-2 my-lg-0">
                <li class="nav-item">
                    <a class="nav-link mr-4" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <button class="btn btn-outline-primary my-2 my-sm-0"
                            onclick="location.href='{% url 'profile_page' user.username %}'">{{ user.username }}</button>
                </li>
            </ul>
        </div>
    {% else %}

    {% endif %}
</nav>

<div style="height:100%;">

    {% block content %}

    {% endblock %}

</div>

</body>
</html>