webserver/badge_project/badge_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from tastypie.api import Api

from api.resources import JoinedEventActivityResource, EarnedBadgeActivityResource, UserResource, BadgeResource, EventResource, ImageResource, AttendeesResource

api_resources = Api(api_name='resources')
api_resources.register(UserResource())
api_resources.register(BadgeResource())
api_resources.register(EventResource())
api_resources.register(ImageResource())
api_resources.register(JoinedEventActivityResource())
api_resources.register(EarnedBadgeActivityResource())
api_resources.register(AttendeesResource())


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('badges/', include('badges.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('events/', include('events.urls')),
    path('api/', include(api_resources.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/badge_project/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventView.as_view(), name='events'),
    path('event_pin/', views.EventPin.as_view(), name='event_pin'),
    path('<int:pk>/event_profile/', views.EventProfile.as_view(), name='event_profile'),
    path('create_event/', views.CreateEvent.as_view(), name='create_event'),
]

webserver/badge_project/users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from .views import LoginView

current_app = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('<username>/profile_page/', views.ProfilePage.as_view(), name='profile_page'),
    path('<username>/profile_page/edit', views.ProfileUpdate.as_view(), name='edit_profile'),
    path('<int:pk>/profile_page/delete/', views.DeleteUser.as_view(), name='delete_profile'),
    url(r'^login/$', LoginView.as_view(), name='login'),
]

webserver/badge_project/events/models.py
from django.db import models
from django.utils.crypto import get_random_string


# Shady
def random():
    rand = get_random_string(5, '0123456789')
    return rand


class Events(models.Model):
    name = models.CharField(max_length=25)
    description = models.CharField(max_length=255)
    active = models.BooleanField(default=1)
    pin = models.IntegerField(unique=True, default=random())
    created_by = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE, related_name='createdBy')
    attendees = models.ManyToManyField('users.CustomUser', through='users.Attendees', related_name='attendingEvents')
    badge = models.ManyToManyField('badges.Badges', through='EventBadges', related_name='eventBadges')


class BadgeRequests(models.Model):
    user = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE, related_name='request')
    event = models.ForeignKey('Events', on_delete=models.CASCADE, related_name='request')
    badge = models.ForeignKey('badges.Badges', on_delete=models.CASCADE, related_name='request')

    def __str__(self):
        return str(self.user) + str(self.event) + str(self.badge)


class EventBadges(models.Model):
    badge = models.ForeignKey('badges.Badges', on_delete=models.CASCADE, related_name='userbadge')
    event = models.ForeignKey('Events', on_delete=models.CASCADE, related_name='event')


class Activity(models.Model):
    user = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE,
                             related_name='%(app_label)s_%(class)s_related',
                             related_query_name='%(app_label)s_%(class)ss')
    event = models.ForeignKey('Events', on_delete=models.CASCADE,
                              related_name='%(app_label)s_%(class)s_related',
                              related_query_name='%(app_label)s_%(class)ss)')
    datetime_earned = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class EarnedBadgeActivity(Activity):
    badge = models.ForeignKey('badges.Badges', on_delete=models.CASCADE, related_name='%(app_label)s_%(class)s_related')

    def __str__(self):
        return 'Just earned the badge: ' + self.badge.name


class JoinedEventActivity(Activity):

    def __str__(self):
        return self.user.username.capitalize() + ' Just joined the event!'

webserver/badge_project/events/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, Column, HTML, Div
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ModelForm, Form, Textarea
from django import forms

from events.models import Events


class CreateEventForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                Div(HTML(
                    """
                    <h2>Create event</h2>
                    """
                ),
                    css_class='text-white',
                )
                ,
                'name',
                'description',
                Field(
                    'badge',
                    template='widgets/multipleCheckboxes.html',
                ),
                Submit('submit', 'Create'),
                css_class='col-lg-6 mx-auto',
            )
        )

    class Meta:
        model = Events
        fields = ('name', 'description', 'badge')
        labels = {
            'name': 'Name',
            'description': 'Description',
            'badge': 'Add badges'
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter a name for the event'}),
            'description': Textarea(attrs={'cols': 40, 'rows': 5, 'placeholder': 'Describe the event here...'}),
        }


class EventPinForm(Form):
    event_field = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': "Please enter the event's pin"}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                'event_field',
                Submit('submit', 'Enter'),
                css_class='col-lg-4 mx-auto font-weight-bold text-center display-4',
            )
        )

    def clean(self):
        cd = self.cleaned_data
        event_pin = cd.get('event_field')
        try:
            Events.objects.filter(pin=event_pin).get()

        except ObjectDoesNotExist:
            self.add_error('event_field', 'Entered pin is not valid!')

        finally:
            return cd


class MultipleForm(forms.Form):
    action = forms.CharField(max_length=60, widget=forms.HiddenInput())


class BadgeRequestForm(MultipleForm):
    badge_id = forms.IntegerField(widget=forms.HiddenInput())


class BadgeApprovalForm(MultipleForm):
    badge_id_as_str = forms.CharField(max_length=60, widget=forms.HiddenInput())


class DeleteBadgeRequestForm(MultipleForm):
    badge_id = forms.IntegerField(widget=forms.HiddenInput())


class RemoveBadgeFromUserForm(MultipleForm):
    badge_id = forms.IntegerField(widget=forms.HiddenInput())
    user_id = forms.IntegerField(widget=forms.HiddenInput())


class EndEventForm(MultipleForm):
    event_id = forms.IntegerField(widget=forms.HiddenInput())


class BadgeApprovalModeratorForm(MultipleForm):
    badge_id = forms.IntegerField(widget=forms.HiddenInput())
    user_id = forms.IntegerField(widget=forms.HiddenInput())

webserver/badge_project/events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import forms
from django.http import HttpResponseRedirect, QueryDict, request
from django.shortcuts import render, render_to_response
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import *
from django.views.generic.detail import SingleObjectMixin, BaseDetailView
from django.views.generic.edit import ModelFormMixin, FormMixin
from django.contrib.auth import get_user
from django.views.generic.edit import ModelFormMixin

from users.models import CustomUser
from users.models import Attendees
from users.models import CustomUser
from users.models import UserBadges

from badges.models import Badges
from .multiforms import MultiFormsView
from .forms import EventPinForm, CreateEventForm, BadgeRequestForm, BadgeApprovalForm, DeleteBadgeRequestForm, \
    BadgeApprovalModeratorForm, RemoveBadgeFromUserForm, EndEventForm
from .models import Events, BadgeRequests, EventBadges, EarnedBadgeActivity, JoinedEventActivity
from .models import random

from django.db import models


class EventView(LoginRequiredMixin, generic.ListView):
    model = Events
    template_name = 'events/my_events.html'

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        current_user = self.request.user
        context['events_historic_list'] = current_user.attendingEvents.all()
        context['events_created_list'] = Events.objects.filter(created_by=current_user)

        return context


class EventPin(LoginRequiredMixin, View):
    template_name = "events/event_pin.html"

    def get(self, request, *args, **kwargs):
        form = EventPinForm()
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = EventPinForm(request.POST)
        context = {"form": form}
        if form.is_valid():
            cd = form.cleaned_data
            event_pin = cd.pop('event_field')
            current_event_id = Events.objects.filter(pin=event_pin).get().id
            current_user = request.user.id
            attendee = Attendees(event_id=current_event_id, user_id=current_user)
            attendee.save()
            JoinedEventActivity.objects.create(event_id=current_event_id, user_id=current_user)
            return HttpResponseRedirect(self.get_success_url(current_event_id))
        return render(request, self.template_name, context)

    def get_success_url(self, pk):
        return reverse('events:event_profile', kwargs={'pk': pk})


class CreateEvent(LoginRequiredMixin, CreateView):
    model = Events
    form_class = CreateEventForm
    success_url = reverse_lazy('events:events')
    template_name = 'events/create_event_form.html'

    # Retrieves the form before it's been successfully posted
    # Adds a new field to the form name "created_by_id"
    # Saves the value with current user's id
    def post(self, request, *args, **kwargs):
        form = CreateEventForm(request.POST)
        context = {"form": form}
        if form.is_valid():
            cd = form.cleaned_data
            name = cd.pop('name')
            description = cd.pop('description')
            badges = cd.pop('badge')
            user_id = request.user.id

            event = Events.objects.create(name=name, description=description, active=1,
                                          created_by_id=user_id, pin=random())

            for badge in badges:
                EventBadges.objects.create(badge_id=badge.id, event_id=event.id)

            Attendees.objects.create(event_id=event.id, user_id=user_id)
            JoinedEventActivity.objects.create(event_id=event.id, user_id=user_id)

            return HttpResponseRedirect(self.get_success_url(event.id))

        return render(request, self.template_name, context)

    def get_success_url(self, pk):
        return reverse('events:event_profile', kwargs={'pk': pk})


class EventProfile(MultiFormsView):
    template_name = 'events/event_profile.html'
    model = Events
    form_classes = {'request_badge': BadgeRequestForm,
                    'approve_badge': BadgeApprovalForm,
                    'delete_badge_request': DeleteBadgeRequestForm,
                    'remove_badge_from_user': RemoveBadgeFromUserForm,
                    'end_event': EndEventForm,
                    'approve_badge_mod': BadgeApprovalModeratorForm,
                    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        parameter_event_id = self.kwargs['pk']
        event_object = Events.objects.all().get(id=parameter_event_id)

        '''Obtain all badges from the relevant badge_requests'''
        badge_request_qs = BadgeRequests.objects.filter(event_id=event_object.id)
        badge_requests = []
        for badge_request in badge_request_qs:
            badge = badge_request.badge
            badge_requests.append(badge)

        user_is_moderator = False
        if self.request.user.id == event_object.created_by_id:
            user_is_moderator = True

        event_badge_list = event_object.event.all()
        user_badge_list = []
        for event_badge in event_badge_list:
            user_badge_qs = event_badge.user_badges.all()
            for user_badge in user_badge_qs:
                    user_badge_list.append(user_badge)

        context['user_is_moderator'] = user_is_moderator
        context['people_joined'] = Attendees.objects.filter(event=event_object.id).count()
        context['attendees'] = Attendees.objects.filter(event=event_object.id)
        context['earned'] = event_object.badge.all().count()
        context['event_name'] = event_object.name
        context['event_desc'] = event_object.description
        context['event_id'] = event_object.id
        context['badge_requests'] = badge_request_qs
        context['requestable_badge'] = event_object.badge.all()
        context['event_pin'] = event_object.pin
        context['user_badge_list'] = user_badge_list
        context['event_active'] = event_object.active


        return context

    def request_badge_form_valid(self, form):
        badge_id = form.cleaned_data.get('badge_id')
        event_id = self.kwargs['pk']

        b = Badges.objects.all().get(id=badge_id)
        e = Events.objects.all().get(id=event_id)
        u = self.request.user
        br = BadgeRequests.objects.create(user=u, event=e, badge=b)
        return HttpResponseRedirect(self.get_success_url())

    def approve_badge_form_valid(self, form):
        badge_id_as_str = form.cleaned_data.get('badge_id_as_str')
        form_name = form.cleaned_data.get('action')
        return HttpResponseRedirect(self.get_success_url())

    def end_event_form_valid(self, form):
        event_id = form.cleaned_data.get('event_id')
        event = Events.objects.get(id=event_id)
        event.active = 0
        event.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self, **kwargs):
        pk = self.kwargs['pk']
        return reverse('events:event_profile', kwargs={'pk': pk})

    def delete_badge_request_form_valid(self, form):
        badge_id = form.cleaned_data.get('badge_id')
        event_id = self.kwargs['pk']
        user_id = self.request.user.id
        b = BadgeRequests.objects.filter(badge_id=badge_id, event_id=event_id, user_id=user_id).get()
        b.delete()

        return HttpResponseRedirect(self.get_success_url())

    def remove_badge_from_user_form_valid(self, form):
        badge_id = form.cleaned_data.get('badge_id')
        event_id = self.kwargs['pk']
        user_id = form.cleaned_data.get('user_id')
        event_badge = EventBadges.objects.get(badge_id=badge_id, event_id=event_id)
        userbadge = UserBadges.objects.filter(event_badge=event_badge, user_id=user_id).get()
        userbadge.delete()

        return HttpResponseRedirect(self.get_success_url())

    def approve_badge_mod_form_valid(self, form):
        badge_id = form.cleaned_data.get('badge_id')
        event_id = self.kwargs['pk']
        user_id = form.cleaned_data.get('user_id')
        event_badge = EventBadges.objects.get(badge_id=badge_id, event_id=event_id)
        UserBadges.objects.create(event_badge=event_badge, user_id=user_id)
        badgeRequest = BadgeRequests.objects.filter(badge_id=badge_id, event_id=event_id, user_id=user_id).get()
        EarnedBadgeActivity.objects.create(badge_id=badge_id, event_id=event_id, user_id=user_id)
        badgeRequest.delete()

        return HttpResponseRedirect(self.get_success_url())

webserver/badge_project/events/templates/events/create_event.html
{% extends "nav/nav.html" %}

{% load crispy_forms_tags %}

{% block content %}

{% crispy form %}

{% endblock %}

webserver/badge_project/events/templates/events/create_event_form.html
{% extends "nav/nav.html" %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container-fluid bg-info pt-4" style="height: 100%;">
        {% crispy form %}
    </div>

{% endblock %}

webserver/badge_project/events/templates/events/event_pin.html
{% extends 'nav/nav.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="pt-5 bg-info height-100" style="height: 100%;">

        {% crispy form %}

    </div>

{% endblock %}

webserver/badge_project/events/templates/events/event_profile.html
{% extends "nav/nav.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'badges/animations.css' %}">

{% block content %}
    <div class="container-fluid fill bg-info">
        <div class="centerThis">
            {% if event_active is False %}
                <div class="row mx-auto mb-6">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4 mt-4 mb-5">
                        <h1 class="text-danger text-center font-weight-bold text-uppercase eventName"
                            style="font-size: 60px">Event has ended!</h1>
                    </div>
                    <div class="col-md-4">
                    </div>
                </div>
            {% endif %}
            <div class="row mx-auto mb-6">
                <div class="col-md-4">
                </div>
                <div class="col-md-4 mt-4 mb-5">
                    <h2 class="text-white text-center font-weight-bold text-uppercase eventName">{{ event_name }}</h2>
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <div class="row mx-auto mt-4 mb-5">
                <div class="col-md-4">
                </div>
                <div class="col-md-4 mb-4">
                    <h3 class="text-white text-center font-weight-bold pb-2">Event pin: </h3>
                    <h3 class="text-white text-center font-weight-light bg-white text-dark pt-3 pb-3">{{ event_pin }}</h3>
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <div class="row mx-auto mt-5 mb-0">
                <div class="col-md-4">
                    <h3 class="text-white text-center font-weight-bold">Badges available: </h3>
                    <h3 class="text-white text-center font-weight-light">{{ requestable_badge.count }}</h3>
                </div>
                <div class="col-md-4 eventDescription">
                    <h3 class="text-white text-center font-weight-bold">Event description: </h3>
                    <h5 class="text-white text-center font-weight-light">{{ event_desc }}</h5>
                </div>
                <div class="col-md-4 mb-5 pb-5">
                    <h3 class="text-white text-center font-weight-bold">Joined event: </h3>
                    <h3 class="text-white text-center font-weight-light">{{ people_joined }}</h3>
                </div>
            </div>
            <div class="row mx-auto mt-5 mb-0" style="width: 80%;">
                <div id="activityFeedContainer" class="col-md-7 scroll veryNiceBox"
                     style="background-image: linear-gradient(141deg, #8e44ad 0%, rgba(142,68,173,0.91) 51%, rgba(142,68,173,0.73) 75%);">
                    <script>let event_id = {{ event_id }};</script>
                    <script type="text/javascript" src="{% static 'badges/activityFeed.js' %}"></script>
                </div>
                <div class="col-md-4 scroll veryNiceBox"
                     style="background-image: linear-gradient(141deg, #8e44adb8 0%, rgba(142,68,173,0.91) 51%, #8E44AD 75%);">
                    <div id="attendeeContainer">
                        <script type="text/javascript" src="{% static 'badges/attendingUsers.js' %}"></script>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid fill bg-success clearfix">
        <div class="row mx-auto mt-0 mb-6">
            <div class="col-md-4 mt-4">
                {% if user_is_moderator %}
                    <button class="btn btn-outline-light btn-md btn-block" onclick="switchEventProfileContent()">
                        User/Mod
                        Display
                    </button>
                    <form method="post">
                        {% csrf_token %}
                        {{ forms.end_event }}
                        <input type="hidden" name="event_id" value={{ event_id }}>
                        <input type="submit" class="btn btn-danger btn-md btn-block mt-2" value="End Event">
                    </form>
                {% endif %}
            </div>
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
            </div>
        </div>

        <div id="eventProfileModContent" style="display: none">

            {% include "events/event_profile_mod.html" %}

        </div>

        <div class="row mt-0 pt-4 justify-content-center">
            <div class="col-lg-5 m-5 p-5">
                <div id="eventProfileUserContent">

                    {% if requestable_badge %}

                        <div class="table-responsive">
                            <h2 class="text-white text-center font-weight-light mb-4">Request a badge: </h2>
                            <table class="table table-striped table-sm text-white  ">
                                {% for badge in requestable_badge %}
                                    <tr>
                                        <th><img src="{{ badge.image }}" width="75" alt="badge_img"></th>
                                        <th>{{ badge.name }}</th>
                                        <th>
                                            <form method="post">
                                                {% csrf_token %}
                                                {{ forms.request_badge }}
                                                <input type="hidden" name="badge_id" value="{{ badge.id }}">
                                                <input class="btn btn-light btn-sm btn-block ml-0 mr-2" type="submit"
                                                       value="Request">
                                            </form>
                                        </th>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    {% else %}

                        <p class="text-center mt-4 p-5 pb-0">No badges to request at the moment...</p>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

webserver/badge_project/events/templates/events/event_profile_mod.html
<div class="row mx-auto pt-0">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        <h1 class="text-center moderatorStyle">Moderator view</h1>
    </div>
    <div class="col-md-4">
    </div>
</div>
<div class="row mx-auto mt-3">
    <div class="col-lg-5 mx-auto">
        <h2 class="text-center text-white font-weight-light">Badge requests</h2>
        {% if badge_requests %}
            <table class="table table-striped mt-4 text-white">
                {% for badge_request in badge_requests %}
                    <tr>
                        <th>{{ badge_request.badge.name|capfirst }}</th>
                        <th>{{ badge_request.user.username|capfirst }}</th>
                        <th>
                            <form method="post">
                                {% csrf_token %}
                                {{ forms.delete_badge_request }}
                                <input type="hidden" name="badge_id" value="{{ badge_request.badge.id }}">
                                <input class="btn btn-light btn-sm btn-block ml-0 mr-2" type="submit" value="Reject">
                            </form>
                            <form method="post">
                                {% csrf_token %}
                                {{ forms.approve_badge_mod }}
                                <input type="hidden" name="badge_id" value="{{ badge_request.badge.id }}">
                                <input type="hidden" name="user_id" value="{{ badge_request.user.id }}">
                                <input class="btn btn-light btn-sm btn-block ml-0 mr-2" type="submit" value="Approve">
                            </form>
                        </th>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p class="text-center">There are no requests for badges!</p>
        {% endif %}
    </div>
</div>
<div class="row mx-auto mt-3 mb-0">
    <div class="col-lg-5 mx-auto">
        <h2 class="text-center text-white font-weight-light">Remove badges from users</h2>
        {% if user_badge_list %}
            <table class="table table-striped table-sm mt-4 text-white">
                {% for user_badge in user_badge_list %}
                    <tr>
                        <th>{{ user_badge.event_badge.badge.name }}</th>
                        <th>{{ user_badge.user.username }}</th>
                        <th>
                            <form method="post">
                                {% csrf_token %}
                                {{ forms.remove_badge_from_user }}
                                <input type="hidden" name="badge_id" value="{{ user_badge.event_badge.badge_id }}">
                                <input type="hidden" name="user_id" value="{{ user_badge.user.id }}">
                                <input type="submit" class="btn btn-light btn-sm btn-block m-1" value="Remove badge">
                            </form>
                        </th>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p class="text-center">There are no removable badges!</p>
        {% endif %}
    </div>
</div>

webserver/badge_project/events/templates/events/my_events.html
{% extends "nav/nav.html" %}

{% block content %}

    <div class="container-fluid fill bg-white h-100">
        <div class="row mx-auto mb-4 mt-0 mr-5 ml-5 pt-4">
            <div class="col text-center">
                <h1>Events</h1>
            </div>
        </div>
        <div class="row mx-auto mb-4 mt-0 mr-5 ml-5 p-4">
            <div class="col text-center">
                <button class="btn btn-outline-info my-2 my-sm-0 mb-3 mt-4"
                        onclick="location.href='{% url 'events:create_event' %}'">CREATE NEW EVENT
                </button>
            </div>
        </div>
        <div class="row mx-auto pl-5 pr-5">
            <div class="col-md-6">
                <h2 class="mb-4">Event History</h2>
                {% if events_historic_list %}
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <tr>
                                <th scope="col">Event Name</th>
                            </tr>

                            {% for event in events_historic_list %}
                                <tr>
                                    <td><a href="{% url 'events:event_profile' event.id %}">{{ event.name }}</a></td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                {% else %}

                    <p>No events are available.</p>

                {% endif %}
            </div>
            <div class="col-md-6">
                <h2 class="mb-4">Events Created</h2>
                {% if events_created_list %}
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <tr>
                                <th scope="col">Event Name</th>
                            </tr>

                            {% for event in events_created_list %}
                                <tr>
                                    <td><a href="{% url 'events:event_profile' event.id %}">{{ event.name }}</a></td>
                                </tr>
                            {% endfor %}

                        </table>
                    </div>

                {% else %}

                    <p>No events are available.</p>

                {% endif %}

            </div>
        </div>
    </div>


{% endblock %}