webserver/badge_project/badge_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from tastypie.api import Api

from api.resources import JoinedEventActivityResource, EarnedBadgeActivityResource, UserResource, BadgeResource, EventResource, ImageResource, AttendeesResource

api_resources = Api(api_name='resources')
api_resources.register(UserResource())
api_resources.register(BadgeResource())
api_resources.register(EventResource())
api_resources.register(ImageResource())
api_resources.register(JoinedEventActivityResource())
api_resources.register(EarnedBadgeActivityResource())
api_resources.register(AttendeesResource())


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('badges/', include('badges.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('events/', include('events.urls')),
    path('api/', include(api_resources.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/badge_project/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventView.as_view(), name='events'),
    path('event_pin/', views.EventPin.as_view(), name='event_pin'),
    path('<int:pk>/event_profile/', views.EventProfile.as_view(), name='event_profile'),
    path('create_event/', views.CreateEvent.as_view(), name='create_event'),
]

webserver/badge_project/users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from .views import LoginView

current_app = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('<username>/profile_page/', views.ProfilePage.as_view(), name='profile_page'),
    path('<username>/profile_page/edit', views.ProfileUpdate.as_view(), name='edit_profile'),
    path('<int:pk>/profile_page/delete/', views.DeleteUser.as_view(), name='delete_profile'),
    url(r'^login/$', LoginView.as_view(), name='login'),
]

webserver/badge_project/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class CustomUser(AbstractUser):
    event_badge = models.ManyToManyField('events.EventBadges', through="UserBadges", related_name='event_badges', blank=True)
    about_me = models.CharField(max_length=255)
    email = models.CharField(max_length=254)
    events = models.ManyToManyField('events.Events', through='Attendees', related_name='attendingEvents')
    badge_request = models.ManyToManyField('badges.Badges', through='events.BadgeRequests', related_name='badge_request')
    color_value = models.CharField(max_length=7, default='#d76565')

    def event_badge_count_of(self, event_id):
        return self.event_badge.filter(event_id=event_id).count()

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse('user', kwargs={'pk': self.pk})


class Attendees(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='attending')
    event = models.ForeignKey('events.Events', on_delete=models.CASCADE, related_name='attending')


class UserBadges(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='userbadge')
    is_showcase = models.BooleanField(default=0)
    date_earned = models.DateTimeField(auto_now_add=True, blank=False)
    event_badge = models.ForeignKey('events.EventBadges', on_delete=models.CASCADE, related_name='user_badges')

webserver/badge_project/users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Submit, HTML, Field, MultiField
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.forms import ModelForm, Textarea, EmailField, BooleanField, CharField, forms

from .models import CustomUser


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class ChangeProfilePageForm(ModelForm):
    badge_id = CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                HTML(
                    """
                    <h2>Edit profile</h2>
                    """,
                ),
                Field('about_me'),
                MultiField(
                    'badge_id',
                    template='users/widgets/multipleCheckboxes.html'
                ),
                MultiField(
                    'color_value',
                    template='users/widgets/colorPicker.html',
                    css_class='p-0 m-0'
                ),
                Submit(
                    'submit', 'Update',
                    css_class="mb-4"
                ),
                css_class='col-lg-8 mx-auto profileBoxes bg-white pt-2',
            )
        )

    class Meta:
        model = CustomUser
        fields = ('about_me',)
        labels = {
            'about_me': 'About me',
        }
        widgets = {
            'about_me': Textarea(attrs={'cols': 40, 'rows': 5, 'placeholder': 'Write something about yourself...'}),
        }

    def clean(self):
        cd = super().clean()
        userbadge_list = self.data.getlist('badge_id')
        color_value = "#" + self.data.get('color_value')
        cd['userbadge_list'] = userbadge_list
        cd['color_value'] = color_value
        if len(self.cleaned_data['userbadge_list']) > 4: # Make sure the user does not select more than 4 badges.
            raise forms.ValidationError('Select no more than 4.')

        return cd


class CustomUserCreationForm(UserCreationForm):
    email = EmailField()
    condition = BooleanField()

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        self.fields['condition'].label = 'We need to store your email address to restore your password'
        self.fields['condition'].help_text = 'Please make sure to <i>check</i> the checkbox before you continue...'

        for fieldname in []:
            self.fields[fieldname].help_text = None

        for fieldname in ['username', 'password1', 'password2', 'condition', 'email']:
            self.fields[fieldname].required = True

        self.helper.layout = Layout(
            Column(
                HTML(
                    """
                    <h2>Create account</h2>
                    """
                ),
                'username',
                'email',
                'password1',
                'password2',
                HTML(
                    """
                    <h4>Read the conditions before continuation</h4>
                    """
                ),
                'condition',
                Submit('submit', 'Sign up', css_class="btn btn-primary btn-block"),
                css_class='col-lg-5 mx-auto mb-4 mt-4',
            )
        )

    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        for fieldname in ['username', 'password']:
            self.fields[fieldname].required = True

        self.helper.layout = Layout(
            Column(
                HTML(
                    """
                    <h2>Login</h2>
                    """
                ),
                'username',
                'password',
                Submit('login', 'Login', css_class="btn btn-primary btn-block"),
            )
        )

webserver/badge_project/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import CustomUser, Attendees, UserBadges
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator

from .forms import CustomUserCreationForm
from badges.models import Badges
from events.models import Events
# from users.models import CustomUser


from .forms import CustomUserCreationForm, ChangeProfilePageForm, LoginForm
from users.models import CustomUser


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class ProfilePage(generic.ListView):
    model = Badges
    template_name = 'users/profile_page.html'

    paginate_by = 5
    context_object_name = "badges_list"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        parameter_username = self.kwargs['username']
        object_user = CustomUser.objects.filter(username=parameter_username).get()

        badges = object_user.userbadge.order_by('date_earned').reverse()   # hoped to reverse the list so I get the latest earned badge first
                                                    # before pagination kicks in... does not work.
        p = Paginator(badges, self.paginate_by)     # paginate the queryset we made earlier
        context['badges_list'] = p.page(context['page_obj'].number)

        '''Obtain all events from the '''
        attendants_qs = Attendees.objects.filter(user_id=object_user.id)
        events_list = []
        for attendants_qs in attendants_qs:
            if attendants_qs.event.active:
                event = attendants_qs.event
                events_list.append(event)

        context['showcase_list'] = object_user.userbadge.filter(is_showcase=1) # for now this has to be overridden
        # context['badges_list'] = object_user.badge.all() # override also override built-in pagination.
        context['event_active_list'] = events_list
        context['about_me'] = object_user.about_me
        context['profile_owner'] = parameter_username

        # User stats
        context['badge_count'] = object_user.event_badge.all().count()
        context['event_count'] = Attendees.objects.filter(user_id=object_user.id).count()
        context['date_joined'] = object_user.date_joined


        return context


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    form_class = ChangeProfilePageForm
    template_name = 'users/profile_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        object_user = self.request.user
        context['user_badge_list'] = object_user.userbadge.all()
        return context

    def get_success_url(self):
        username = self.kwargs['username']
        return reverse('profile_page', kwargs={'username': username})

    def post(self, request, *args, **kwargs):
        form = ChangeProfilePageForm(request.POST)
        context = {"form": form}
        if form.is_valid():
            cd = form.cleaned_data
            userbadge_list_all = UserBadges.objects.filter(user_id=self.request.user.id)
            userbadge_list_add = cd.pop('userbadge_list')

            user = self.request.user
            about_me = cd.pop('about_me')
            user.about_me = about_me
            user.color_value = cd.pop('color_value')
            user.save()

            for userbadge in userbadge_list_all:

                if str(userbadge.id) in userbadge_list_add:
                    new_userbadge = UserBadges.objects.get(id=userbadge.id)
                    new_userbadge.is_showcase = 1
                    new_userbadge.save()
                else:
                    userbadge.is_showcase = 0
                    userbadge.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, **kwargs):
        return get_object_or_404(CustomUser, pk=self.request.user.id)


class DeleteUser(DeleteView):
    model = CustomUser
    template_name = 'users/profile_delete_form.html'

    def get_success_url(self):
        user_id = self.request.user.id
        user = CustomUser.objects.filter(id=user_id)
        user.delete()
        return reverse_lazy('login')
    #
    # def get_object(self, **kwargs):
    #     return get_object_or_404(CustomUser, pk=self.request.user.id)


class CreateNewBadge:
    form_class = ChangeProfilePageForm
    template_name = 'users/profile_update_form.html'


class LoginView(generic.FormView):
    form_class = LoginForm
    success_url = reverse_lazy('home')
    template_name = 'registration/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)

webserver/badge_project/users/templates/users/profile_delete_form.html
{% extends "nav/nav.html" %}

{% load crispy_forms_tags %}

{% block content %}



    <script>
        function goBack() {
            window.history.back();
        }
    </script>

    <div class="container">
        <div class="row mt-4 mx-auto ">
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <div class="row mt-4">
                    <h2>Delete account</h2>
                    <p>Are you sure you want to delete "{{ object.username }}"?</p>
                </div>
                <div class="row mt-2">
                    <form  class="form-control border-0 mb-3 p-0" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-lg btn-block">Confirm</button>
                    </form>
                    <button type="button" class="btn btn-success btn-lg btn-block" onclick="goBack()">Go back</button>
                </div>

            </div>
            <div class="col-md-4">
            </div>
            </div>
        </div>

{% endblock %}

webserver/badge_project/users/templates/users/profile_page.html
{% extends "nav/nav.html" %}

{% block content %}
    {% load static %}


    <div style="background-color: {{ user.color_value }}" class="container-fluid p-0">
    <div class="container pt-4" style="height: auto; overflow: auto;">

        <div class="row p-0">
            <div class="col">
                <div class="row m-0">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-9">
                <img width="85px" src="/images/avatars/avatar.png" id="avatar" alt="Avatar picture"
                     style="border-radius: 5px; border-color: #0069d982; border-width: 3px; border-style: solid;">
                <h2 class="text-right text-info mt-4 ml-4" style="display: inline;">{{ profile_owner }}</h2>
            </div>
            <div class="col-lg-3">
                <a class="btn btn-primary btn-md btn-block" href="{% url 'edit_profile' user.username %}"
                   role="button">Edit
                    profile</a>
            </div>
        </div>


        <div class="row mt-4">
            <div class="col-lg-9">

                <div>
                    <div class="bg-white text-dark pt-4 pr-4 pl-4 profileBoxes">
                        <h2 class="text-left">Showcase</h2>
                        <div>
                            {% if showcase_list %}
                                <div class="table-responsive">
                                    <table class="table table-borderless showcaseTable">
                                        <tr>
                                            {% for userbadge in showcase_list %}
                                                <td style="border-top-width: 0;"><img
                                                        src="{{ userbadge.event_badge.badge.image.url }}"
                                                        width="150"
                                                        alt="Picture is missing, did the developer assign the wrong path?">
                                                    <p class="pt-2">{{ userbadge.event_badge.badge.description }}</p>
                                                </td>
                                            {% endfor %}
                                        </tr>
                                    </table>
                                </div>
                            {% else %}
                                <p class="pb-4">No badges are available.</p>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col">
                            <div class="bg-white text-dark p-4 profileBoxes">
                                <h2>About me</h2>
                                <p>
                                    {{ about_me }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col">
                            <div class="bg-white text-dark p-4 profileBoxes mb-4">
                                <h2>Recently earned badges</h2>
                                <div class="table-responsive">
                                    {% if badges_list %}

                                        <table class="table table-borderless">
                                            {% for user_badge in badges_list %}
                                                <tr>
                                                    <td style="border-top-width: 0; vertical-align: baseline;">
                                                        <img src="{{ user_badge.event_badge.badge.image.url }}"
                                                             width="100"
                                                             alt="Picture is missing, did the developer assign the wrong path?">
                                                    </td>
                                                    <td style="border-top-width: 0; vertical-align: baseline;">{{ user_badge.event_badge.badge.name }}</td>
                                                </tr>
                                            {% endfor %}
                                            <div class="pagination">
                                        <span class="step-links">
                                            {% if badges_list.has_previous %}
                                                <a href="?page=1">&laquo; first</a>
                                                <a href="?page={{ badges_list.previous_page_number }}">previous</a>
                                            {% endif %}

                                            <span class="current">
                                                Page {{ badges_list.number }} of {{ badges_list.paginator.num_pages }}.
                                            </span>

                                            {% if badges_list.has_next %}
                                                <a href="?page={{ badges_list.next_page_number }}">next</a>
                                                <a href="?page={{ badges_list.paginator.num_pages }}">last &raquo;</a>
                                            {% endif %}
                                        </span>
                                            </div>
                                        </table>

                                    {% else %}
                                        <p>No badges are available.</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-lg-3">
                <div class="bg-white text-dark p-4 profileBoxes">
                    <h2 class="text-left">Statistics</h2>
                    <div>
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th scope="col"> Badges Earned: {{ badge_count }}</th>
                            </tr>
                            <tr>
                                <th scope="col"> Events Participated: {{ event_count }}</th>
                            </tr>
                            <tr>
                                <th scope="col"> Date Joined: {{ date_joined }}</th>
                            </tr>
                            </thead>
                        </table>
                    </div>

                    <div class="bg-white text-dark pt-2">
                        <h2>Active events</h2>
                        <div class="table-responsive">
                            {% if event_active_list %}
                                <table class="table table-bordered">
                                    <thead>
                                    {% for event in event_active_list %}
                                        <tr>
                                            <th>
                                                <a href="{% url 'events:event_profile' event.id %}">{{ event.name }}</a>
                                            </th>
                                        </tr>
                                    {% endfor %}
                                    </thead>
                                </table>

                            {% else %}

                                <p>No events are available.</p>

                            {% endif %}
                        </div>
                    </div>
                    <div>
                        <!--  share button -->
                        <div class="d-flex justify-content-right mb-2">
                            <div class="fb-share-button"
                                 data-layout="button" data-size="small">
                                <a target="_blank"
                                   href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F192.168.50.50%3A8080%2Fusers%2F<username>%2Fprofile_page%2F&amp;src=sdkpreparse"
                                   class="fb-xfbml-parse-ignore">Share</a>
                            </div>
                        </div>
                        <!-- share button -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

webserver/badge_project/users/templates/users/profile_update_form.html
{% extends "nav/nav.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container mb-4 mt-4">

        {% crispy form %}

        <!-- Delte button -->
        <form method="get" action="{% url 'delete_profile' user.id %}">
            <div class="row justify-content-end">
                <div class="col-lg-4">
                    <button type="submit" class="btn btn-danger">Delete my account</button>
                </div>
            </div>
        </form>

    </div>

{% endblock %}